### ISSUE TITLE
カスタムクラスアイコンをノードに表示してほしい

### ISSUE THREAD

**Issue by AheadGameStudio** [folt-a/godot-project-design-links#1]
![image](https://user-images.githubusercontent.com/186786/200107997-ac38f44d-dcbb-4250-96a6-820ccdaea76c.png)

![image](https://user-images.githubusercontent.com/186786/200108010-18acc871-fa1d-4e70-95fc-ede25fce9e48.png)

カスタムクラスに設定したアイコンをノードのアイコンとして表示してほしいです！

**Comment by folt-a** [comment]
`@icon`を設定したスクリプトとそのスクリプトをルートノードにつけたシーンをドロップするとアイコンが反映されるようになりました。

現時点では、`@icon`を設定したスクリプトのクラスをextendsしたスクリプト・シーンでは反映されません。  
（このスクリプトに別途`@icon`があれば、それが反映されます）

また、スクリプトをテキストとして読み取ってアイコンのパスを取得しているため、毎回やると重くなるので、
キャッシュ処理として初回アイコン画像読み取り時に、画像のパスを設定ファイルに含めて保存しています。

そのため、アイコンが変更されてももとのアイコンが表示され続けます。
アイコンが変更したい場合は一度消して保存し、再度ドロップして追加する必要があります。

![image](https://user-images.githubusercontent.com/32963227/200132067-c18dc5f2-d6b3-4b46-ab32-81f230d17f6d.png)
